### PR TITLE
Fix cfRef Resolver

### PR DESCRIPTION
**Pull request by bboure**
@lightsofapollo as discussed in #112 
This fixes my issue

### CODE REVIEW

**Comment by pianomansam** [comment]
I've confirmed that using this fix on the `fix-Ref-resolver` branch also resolves the issue for me.

**Comment by cbaron** [comment]
I don't have much context on this issue, but LGTM.

**Comment by bboure** [comment]
I had more issue because of the other Exceptions
I think I would remove them all and just return `value` in those cases.

**Comment by lightsofapollo** [comment]
Nice thank you for the fix

**Comment by lightsofapollo** [comment]
@bboure Can you update the test checking for this and potentially add a test with the case that effected you? I want to make sure we do not regress this behavior.

**Comment by bboure** [comment]
@lightsofapollo I added test based on my use case.

**Comment by lightsofapollo** [comment]
@bboure Looks good to me! Ship it!

**Comment by bboure** [comment]
merged and version bumped.

**Pull request merged**
