### PR TITLE
Added flatten function for mappingTemplates and dataSrouces

### PR DESCRIPTION
**Pull request by devmetal**
This closes: #86 I think :) 

This is needed for handle this kind of configs:

https://github.com/sid88in/serverless-appsync-plugin/pull/182

### CODE REVIEW

**Comment by bboure** [comment]
Thanks @devmetal 
I was wondering if instead of duplicating code across both repos and also taking the risk of it breaking again if something ever changes again in the plugin, the emulator should rely on the appsync plugin in order to "parse" the yml file.
Plugin could expose a function that returns a standardised resource with everything the emulator needs: datasources, templates, schema, functions, etc.

**Comment by bboure** [comment]
Otherwise, I tested this and seems to work! 😄 🎢

**Comment by lightsofapollo** [comment]
Love it

**Comment by lightsofapollo** [comment]
@devmetal I am happy to land this as is but I can't promise we won't break this functionality (either via contribution or us) without some minimal test. Is there some easy way we can add a test for this ?

**Comment by devmetal** [comment]
@lightsofapollo Hi :) Thank you for feedback, i tried to make this more centralized. I saw there are already have some test for load config, and i moved the base logic in to it. What do you think? I added unit tests and also tested on local. :) Thank you

**Comment by bboure** [comment]
Great @devmetal and Thanks
Moving the flatten into load loadConfig will break my PR #92 😄 (because would not be called).
In case my PR gets positive feedback, we should sync in order to fix this.

**Comment by lightsofapollo** [comment]
@devmetal This looks great now but it probably needs to be rebased to avoid the problem @bboure mentioned (that PR has landed).

**Comment by devmetal** [comment]
@lightsofapollo @bboure Hi, i rebased and merged my branch. What we wanna do next? :smile: 
That was the rebase that you think?

Thank you :)

**Comment by lightsofapollo** [comment]
Released in 0.9.0

**Pull request merged**
